//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje1Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Educationid { get; set; }
        public string Title { get; set; }
        public string EducationDate { get; set; }
        public string Subbitle { get; set; }
        public string Description { get; set; }
    }
}
