//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje1Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messagetbl
    {
        public int Messageid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phonenumber { get; set; }
        public string subject { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> senddate { get; set; }
        public Nullable<bool> isread { get; set; }
        public Nullable<int> categoryid { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
