//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Proje1Portfolio.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class myportfolioEntities7 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new myportfolioEntities7 object using the connection string found in the 'myportfolioEntities7' section of the application configuration file.
        /// </summary>
        public myportfolioEntities7() : base("name=myportfolioEntities7", "myportfolioEntities7")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new myportfolioEntities7 object.
        /// </summary>
        public myportfolioEntities7(string connectionString) : base(connectionString, "myportfolioEntities7")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new myportfolioEntities7 object.
        /// </summary>
        public myportfolioEntities7(EntityConnection connection) : base(connection, "myportfolioEntities7")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<About> About
        {
            get
            {
                if ((_About == null))
                {
                    _About = base.CreateObjectSet<About>("About");
                }
                return _About;
            }
        }
        private ObjectSet<About> _About;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Category
        {
            get
            {
                if ((_Category == null))
                {
                    _Category = base.CreateObjectSet<Category>("Category");
                }
                return _Category;
            }
        }
        private ObjectSet<Category> _Category;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Education> Education
        {
            get
            {
                if ((_Education == null))
                {
                    _Education = base.CreateObjectSet<Education>("Education");
                }
                return _Education;
            }
        }
        private ObjectSet<Education> _Education;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Experience> Experience
        {
            get
            {
                if ((_Experience == null))
                {
                    _Experience = base.CreateObjectSet<Experience>("Experience");
                }
                return _Experience;
            }
        }
        private ObjectSet<Experience> _Experience;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<messagetbl> messagetbl
        {
            get
            {
                if ((_messagetbl == null))
                {
                    _messagetbl = base.CreateObjectSet<messagetbl>("messagetbl");
                }
                return _messagetbl;
            }
        }
        private ObjectSet<messagetbl> _messagetbl;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Profile> Profile
        {
            get
            {
                if ((_Profile == null))
                {
                    _Profile = base.CreateObjectSet<Profile>("Profile");
                }
                return _Profile;
            }
        }
        private ObjectSet<Profile> _Profile;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Service> Service
        {
            get
            {
                if ((_Service == null))
                {
                    _Service = base.CreateObjectSet<Service>("Service");
                }
                return _Service;
            }
        }
        private ObjectSet<Service> _Service;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Skill> Skill
        {
            get
            {
                if ((_Skill == null))
                {
                    _Skill = base.CreateObjectSet<Skill>("Skill");
                }
                return _Skill;
            }
        }
        private ObjectSet<Skill> _Skill;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Testimonial> Testimonial
        {
            get
            {
                if ((_Testimonial == null))
                {
                    _Testimonial = base.CreateObjectSet<Testimonial>("Testimonial");
                }
                return _Testimonial;
            }
        }
        private ObjectSet<Testimonial> _Testimonial;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Work> Work
        {
            get
            {
                if ((_Work == null))
                {
                    _Work = base.CreateObjectSet<Work>("Work");
                }
                return _Work;
            }
        }
        private ObjectSet<Work> _Work;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the About EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAbout(About about)
        {
            base.AddObject("About", about);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Category EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategory(Category category)
        {
            base.AddObject("Category", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Education EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEducation(Education education)
        {
            base.AddObject("Education", education);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Experience EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExperience(Experience experience)
        {
            base.AddObject("Experience", experience);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the messagetbl EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomessagetbl(messagetbl messagetbl)
        {
            base.AddObject("messagetbl", messagetbl);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Profile EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfile(Profile profile)
        {
            base.AddObject("Profile", profile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Service EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToService(Service service)
        {
            base.AddObject("Service", service);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Skill EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSkill(Skill skill)
        {
            base.AddObject("Skill", skill);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Testimonial EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTestimonial(Testimonial testimonial)
        {
            base.AddObject("Testimonial", testimonial);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Work EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWork(Work work)
        {
            base.AddObject("Work", work);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myportfolioModel1", Name="About")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class About : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new About object.
        /// </summary>
        /// <param name="aboutid">Initial value of the Aboutid property.</param>
        public static About CreateAbout(global::System.Int32 aboutid)
        {
            About about = new About();
            about.Aboutid = aboutid;
            return about;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Aboutid
        {
            get
            {
                return _Aboutid;
            }
            set
            {
                if (_Aboutid != value)
                {
                    OnAboutidChanging(value);
                    ReportPropertyChanging("Aboutid");
                    _Aboutid = StructuralObject.SetValidValue(value, "Aboutid");
                    ReportPropertyChanged("Aboutid");
                    OnAboutidChanged();
                }
            }
        }
        private global::System.Int32 _Aboutid;
        partial void OnAboutidChanging(global::System.Int32 value);
        partial void OnAboutidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Detail
        {
            get
            {
                return _Detail;
            }
            set
            {
                OnDetailChanging(value);
                ReportPropertyChanging("Detail");
                _Detail = StructuralObject.SetValidValue(value, true, "Detail");
                ReportPropertyChanged("Detail");
                OnDetailChanged();
            }
        }
        private global::System.String _Detail;
        partial void OnDetailChanging(global::System.String value);
        partial void OnDetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true, "ImageUrl");
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myportfolioModel1", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryid">Initial value of the Categoryid property.</param>
        public static Category CreateCategory(global::System.Int32 categoryid)
        {
            Category category = new Category();
            category.Categoryid = categoryid;
            return category;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Categoryid
        {
            get
            {
                return _Categoryid;
            }
            set
            {
                if (_Categoryid != value)
                {
                    OnCategoryidChanging(value);
                    ReportPropertyChanging("Categoryid");
                    _Categoryid = StructuralObject.SetValidValue(value, "Categoryid");
                    ReportPropertyChanged("Categoryid");
                    OnCategoryidChanged();
                }
            }
        }
        private global::System.Int32 _Categoryid;
        partial void OnCategoryidChanging(global::System.Int32 value);
        partial void OnCategoryidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, true, "CategoryName");
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myportfolioModel1", Name="Education")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Education : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Education object.
        /// </summary>
        /// <param name="educationid">Initial value of the Educationid property.</param>
        public static Education CreateEducation(global::System.Int32 educationid)
        {
            Education education = new Education();
            education.Educationid = educationid;
            return education;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Educationid
        {
            get
            {
                return _Educationid;
            }
            set
            {
                if (_Educationid != value)
                {
                    OnEducationidChanging(value);
                    ReportPropertyChanging("Educationid");
                    _Educationid = StructuralObject.SetValidValue(value, "Educationid");
                    ReportPropertyChanged("Educationid");
                    OnEducationidChanged();
                }
            }
        }
        private global::System.Int32 _Educationid;
        partial void OnEducationidChanging(global::System.Int32 value);
        partial void OnEducationidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EducationDate
        {
            get
            {
                return _EducationDate;
            }
            set
            {
                OnEducationDateChanging(value);
                ReportPropertyChanging("EducationDate");
                _EducationDate = StructuralObject.SetValidValue(value, true, "EducationDate");
                ReportPropertyChanged("EducationDate");
                OnEducationDateChanged();
            }
        }
        private global::System.String _EducationDate;
        partial void OnEducationDateChanging(global::System.String value);
        partial void OnEducationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subbitle
        {
            get
            {
                return _Subbitle;
            }
            set
            {
                OnSubbitleChanging(value);
                ReportPropertyChanging("Subbitle");
                _Subbitle = StructuralObject.SetValidValue(value, true, "Subbitle");
                ReportPropertyChanged("Subbitle");
                OnSubbitleChanged();
            }
        }
        private global::System.String _Subbitle;
        partial void OnSubbitleChanging(global::System.String value);
        partial void OnSubbitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myportfolioModel1", Name="Experience")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Experience : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Experience object.
        /// </summary>
        /// <param name="experienceid">Initial value of the Experienceid property.</param>
        public static Experience CreateExperience(global::System.Int32 experienceid)
        {
            Experience experience = new Experience();
            experience.Experienceid = experienceid;
            return experience;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Experienceid
        {
            get
            {
                return _Experienceid;
            }
            set
            {
                if (_Experienceid != value)
                {
                    OnExperienceidChanging(value);
                    ReportPropertyChanging("Experienceid");
                    _Experienceid = StructuralObject.SetValidValue(value, "Experienceid");
                    ReportPropertyChanged("Experienceid");
                    OnExperienceidChanged();
                }
            }
        }
        private global::System.Int32 _Experienceid;
        partial void OnExperienceidChanging(global::System.Int32 value);
        partial void OnExperienceidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, true, "CompanyName");
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WorkDate
        {
            get
            {
                return _WorkDate;
            }
            set
            {
                OnWorkDateChanging(value);
                ReportPropertyChanging("WorkDate");
                _WorkDate = StructuralObject.SetValidValue(value, true, "WorkDate");
                ReportPropertyChanged("WorkDate");
                OnWorkDateChanged();
            }
        }
        private global::System.String _WorkDate;
        partial void OnWorkDateChanging(global::System.String value);
        partial void OnWorkDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myportfolioModel1", Name="messagetbl")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class messagetbl : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new messagetbl object.
        /// </summary>
        /// <param name="messageid">Initial value of the Messageid property.</param>
        public static messagetbl Createmessagetbl(global::System.Int32 messageid)
        {
            messagetbl messagetbl = new messagetbl();
            messagetbl.Messageid = messageid;
            return messagetbl;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Messageid
        {
            get
            {
                return _Messageid;
            }
            set
            {
                if (_Messageid != value)
                {
                    OnMessageidChanging(value);
                    ReportPropertyChanging("Messageid");
                    _Messageid = StructuralObject.SetValidValue(value, "Messageid");
                    ReportPropertyChanged("Messageid");
                    OnMessageidChanged();
                }
            }
        }
        private global::System.Int32 _Messageid;
        partial void OnMessageidChanging(global::System.Int32 value);
        partial void OnMessageidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phonenumber
        {
            get
            {
                return _phonenumber;
            }
            set
            {
                OnphonenumberChanging(value);
                ReportPropertyChanging("phonenumber");
                _phonenumber = StructuralObject.SetValidValue(value, true, "phonenumber");
                ReportPropertyChanged("phonenumber");
                OnphonenumberChanged();
            }
        }
        private global::System.String _phonenumber;
        partial void OnphonenumberChanging(global::System.String value);
        partial void OnphonenumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String subject
        {
            get
            {
                return _subject;
            }
            set
            {
                OnsubjectChanging(value);
                ReportPropertyChanging("subject");
                _subject = StructuralObject.SetValidValue(value, true, "subject");
                ReportPropertyChanged("subject");
                OnsubjectChanged();
            }
        }
        private global::System.String _subject;
        partial void OnsubjectChanging(global::System.String value);
        partial void OnsubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detail
        {
            get
            {
                return _detail;
            }
            set
            {
                OndetailChanging(value);
                ReportPropertyChanging("detail");
                _detail = StructuralObject.SetValidValue(value, true, "detail");
                ReportPropertyChanged("detail");
                OndetailChanged();
            }
        }
        private global::System.String _detail;
        partial void OndetailChanging(global::System.String value);
        partial void OndetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> senddate
        {
            get
            {
                return _senddate;
            }
            set
            {
                OnsenddateChanging(value);
                ReportPropertyChanging("senddate");
                _senddate = StructuralObject.SetValidValue(value, "senddate");
                ReportPropertyChanged("senddate");
                OnsenddateChanged();
            }
        }
        private Nullable<global::System.DateTime> _senddate;
        partial void OnsenddateChanging(Nullable<global::System.DateTime> value);
        partial void OnsenddateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isread
        {
            get
            {
                return _isread;
            }
            set
            {
                OnisreadChanging(value);
                ReportPropertyChanging("isread");
                _isread = StructuralObject.SetValidValue(value, "isread");
                ReportPropertyChanged("isread");
                OnisreadChanged();
            }
        }
        private Nullable<global::System.Boolean> _isread;
        partial void OnisreadChanging(Nullable<global::System.Boolean> value);
        partial void OnisreadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> categoryid
        {
            get
            {
                return _categoryid;
            }
            set
            {
                OncategoryidChanging(value);
                ReportPropertyChanging("categoryid");
                _categoryid = StructuralObject.SetValidValue(value, "categoryid");
                ReportPropertyChanged("categoryid");
                OncategoryidChanged();
            }
        }
        private Nullable<global::System.Int32> _categoryid;
        partial void OncategoryidChanging(Nullable<global::System.Int32> value);
        partial void OncategoryidChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myportfolioModel1", Name="Profile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Profile object.
        /// </summary>
        /// <param name="profileid">Initial value of the Profileid property.</param>
        public static Profile CreateProfile(global::System.Int32 profileid)
        {
            Profile profile = new Profile();
            profile.Profileid = profileid;
            return profile;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Profileid
        {
            get
            {
                return _Profileid;
            }
            set
            {
                if (_Profileid != value)
                {
                    OnProfileidChanging(value);
                    ReportPropertyChanging("Profileid");
                    _Profileid = StructuralObject.SetValidValue(value, "Profileid");
                    ReportPropertyChanged("Profileid");
                    OnProfileidChanged();
                }
            }
        }
        private global::System.Int32 _Profileid;
        partial void OnProfileidChanging(global::System.Int32 value);
        partial void OnProfileidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true, "Address");
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true, "PhoneNumber");
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Github
        {
            get
            {
                return _Github;
            }
            set
            {
                OnGithubChanging(value);
                ReportPropertyChanging("Github");
                _Github = StructuralObject.SetValidValue(value, true, "Github");
                ReportPropertyChanged("Github");
                OnGithubChanged();
            }
        }
        private global::System.String _Github;
        partial void OnGithubChanging(global::System.String value);
        partial void OnGithubChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true, "ImageUrl");
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MapLocation
        {
            get
            {
                return _MapLocation;
            }
            set
            {
                OnMapLocationChanging(value);
                ReportPropertyChanging("MapLocation");
                _MapLocation = StructuralObject.SetValidValue(value, true, "MapLocation");
                ReportPropertyChanged("MapLocation");
                OnMapLocationChanged();
            }
        }
        private global::System.String _MapLocation;
        partial void OnMapLocationChanging(global::System.String value);
        partial void OnMapLocationChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myportfolioModel1", Name="Service")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Service : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Service object.
        /// </summary>
        /// <param name="serviceid">Initial value of the Serviceid property.</param>
        public static Service CreateService(global::System.Int32 serviceid)
        {
            Service service = new Service();
            service.Serviceid = serviceid;
            return service;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Serviceid
        {
            get
            {
                return _Serviceid;
            }
            set
            {
                if (_Serviceid != value)
                {
                    OnServiceidChanging(value);
                    ReportPropertyChanging("Serviceid");
                    _Serviceid = StructuralObject.SetValidValue(value, "Serviceid");
                    ReportPropertyChanged("Serviceid");
                    OnServiceidChanged();
                }
            }
        }
        private global::System.Int32 _Serviceid;
        partial void OnServiceidChanging(global::System.Int32 value);
        partial void OnServiceidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Icon
        {
            get
            {
                return _Icon;
            }
            set
            {
                OnIconChanging(value);
                ReportPropertyChanging("Icon");
                _Icon = StructuralObject.SetValidValue(value, true, "Icon");
                ReportPropertyChanged("Icon");
                OnIconChanged();
            }
        }
        private global::System.String _Icon;
        partial void OnIconChanging(global::System.String value);
        partial void OnIconChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myportfolioModel1", Name="Skill")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Skill : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Skill object.
        /// </summary>
        /// <param name="skillid">Initial value of the Skillid property.</param>
        public static Skill CreateSkill(global::System.Int32 skillid)
        {
            Skill skill = new Skill();
            skill.Skillid = skillid;
            return skill;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Skillid
        {
            get
            {
                return _Skillid;
            }
            set
            {
                if (_Skillid != value)
                {
                    OnSkillidChanging(value);
                    ReportPropertyChanging("Skillid");
                    _Skillid = StructuralObject.SetValidValue(value, "Skillid");
                    ReportPropertyChanged("Skillid");
                    OnSkillidChanged();
                }
            }
        }
        private global::System.Int32 _Skillid;
        partial void OnSkillidChanging(global::System.Int32 value);
        partial void OnSkillidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Icon
        {
            get
            {
                return _Icon;
            }
            set
            {
                OnIconChanging(value);
                ReportPropertyChanging("Icon");
                _Icon = StructuralObject.SetValidValue(value, true, "Icon");
                ReportPropertyChanged("Icon");
                OnIconChanged();
            }
        }
        private global::System.String _Icon;
        partial void OnIconChanging(global::System.String value);
        partial void OnIconChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, "Value");
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private Nullable<global::System.Byte> _Value;
        partial void OnValueChanging(Nullable<global::System.Byte> value);
        partial void OnValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myportfolioModel1", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myportfolioModel1", Name="Testimonial")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Testimonial : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Testimonial object.
        /// </summary>
        /// <param name="testimonianiaid">Initial value of the Testimonianiaid property.</param>
        public static Testimonial CreateTestimonial(global::System.Int32 testimonianiaid)
        {
            Testimonial testimonial = new Testimonial();
            testimonial.Testimonianiaid = testimonianiaid;
            return testimonial;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Testimonianiaid
        {
            get
            {
                return _Testimonianiaid;
            }
            set
            {
                if (_Testimonianiaid != value)
                {
                    OnTestimonianiaidChanging(value);
                    ReportPropertyChanging("Testimonianiaid");
                    _Testimonianiaid = StructuralObject.SetValidValue(value, "Testimonianiaid");
                    ReportPropertyChanged("Testimonianiaid");
                    OnTestimonianiaidChanged();
                }
            }
        }
        private global::System.Int32 _Testimonianiaid;
        partial void OnTestimonianiaidChanging(global::System.Int32 value);
        partial void OnTestimonianiaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true, "Comment");
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true, "ImageUrl");
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myportfolioModel1", Name="Work")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Work : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Work object.
        /// </summary>
        /// <param name="workid">Initial value of the Workid property.</param>
        public static Work CreateWork(global::System.Int32 workid)
        {
            Work work = new Work();
            work.Workid = workid;
            return work;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Workid
        {
            get
            {
                return _Workid;
            }
            set
            {
                if (_Workid != value)
                {
                    OnWorkidChanging(value);
                    ReportPropertyChanging("Workid");
                    _Workid = StructuralObject.SetValidValue(value, "Workid");
                    ReportPropertyChanged("Workid");
                    OnWorkidChanged();
                }
            }
        }
        private global::System.Int32 _Workid;
        partial void OnWorkidChanging(global::System.Int32 value);
        partial void OnWorkidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripton
        {
            get
            {
                return _Descripton;
            }
            set
            {
                OnDescriptonChanging(value);
                ReportPropertyChanging("Descripton");
                _Descripton = StructuralObject.SetValidValue(value, true, "Descripton");
                ReportPropertyChanged("Descripton");
                OnDescriptonChanged();
            }
        }
        private global::System.String _Descripton;
        partial void OnDescriptonChanging(global::System.String value);
        partial void OnDescriptonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true, "ImageUrl");
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GithubUrl
        {
            get
            {
                return _GithubUrl;
            }
            set
            {
                OnGithubUrlChanging(value);
                ReportPropertyChanging("GithubUrl");
                _GithubUrl = StructuralObject.SetValidValue(value, true, "GithubUrl");
                ReportPropertyChanged("GithubUrl");
                OnGithubUrlChanged();
            }
        }
        private global::System.String _GithubUrl;
        partial void OnGithubUrlChanging(global::System.String value);
        partial void OnGithubUrlChanged();

        #endregion

    }

    #endregion

}
