//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje1Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public int ıd { get; set; }
        public string title { get; set; }
        public string ICON { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string Url { get; set; }
    }
}
